engines:
  coffeelint:
    enabled: true
  css-lint:
      enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
      - javascript
    exclude_paths:
      # Currently ignore folder due to third party libraries
      - interactives/
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  phpcodesniffer:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.md"
  - "**.php"
  - "**.scss"
exclude_paths:
- "**/third-party/**/*"
