sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.11.2
language: python
python:
  - '3.6'
before_install:
  # See https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg
install:
  - sudo docker --version
  - sudo docker-compose --version
jobs:
  include:
    - stage: test
      script: ./csfg ci test_suite
    - script: ./csfg ci test_backwards
      if: type = pull_request
    - script: ./csfg ci style
    - script: ./csfg ci docs
notifications:
  email: false
  slack:
    rooms: deptfunstuff:abJKvzApk5SKtcEyAgtswXAv
    on_success: change
    on_failure: change
stages:
  - name: test