sudo: required
services:
  - docker
language: python
python:
  - '3.6'
before_install:
  # See https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg
install:
  - sudo docker --version
  - sudo docker-compose --version
jobs:
  include:
    - stage: test
      script: ./csfg ci load_content
    - script: ./csfg ci test_general
    - script: ./csfg ci test_management
    - script: ./csfg ci test_backwards
      if: type = pull_request
    - script: ./csfg ci style
    - script: ./csfg ci docs
    - stage: develop deploy
      script: skip
      deploy:
        - provider: script
          script: bash ./infrastructure/dev-deploy/deploy-app.sh
          skip_cleanup: true
          on:
            branch: develop
    - script: skip
      deploy:
        - provider: script
          script: bash ./infrastructure/dev-deploy/deploy-static-files.sh
          skip_cleanup: true
          on:
            branch: develop
    - script: skip
      deploy:
        - provider: script
          script: bash ./infrastructure/dev-deploy/update-database.sh
          skip_cleanup: true
          on:
            branch: develop
notifications:
  email: false
  slack:
    rooms: deptfunstuff:abJKvzApk5SKtcEyAgtswXAv
    on_success: change
    on_failure: change
stages:
  - name: test
