runtime: custom
env: flex

beta_settings:
    cloud_sql_instances: ${GOOGLE_CLOUD_SQL_CONNECTION_NAME}

env_variables:
  INCLUDE_INCONTEXT_L10N: ${INCLUDE_INCONTEXT_L10N}
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  GOOGLE_CLOUD_SQL_DATABASE_USERNAME: ${GOOGLE_CLOUD_SQL_DATABASE_USERNAME}
  GOOGLE_CLOUD_SQL_DATABASE_PASSWORD: ${GOOGLE_CLOUD_SQL_DATABASE_PASSWORD}
  GOOGLE_CLOUD_SQL_CONNECTION_NAME: ${GOOGLE_CLOUD_SQL_CONNECTION_NAME}
  GOOGLE_CLOUD_STORAGE_BUCKET_NAME: cs-field-guide.appspot.com

resources:
  cpu: 1
  memory_gb: 3.75

liveness_check:
  path: "/_ah/health"
  check_interval_sec: 5

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
