version: '3'
services:
  cloud_sql_proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    volumes:
      - .:/cs-field-guide
    command: /cloud_sql_proxy -instances=${GOOGLE_CLOUD_SQL_CONNECTION_NAME}=tcp:0.0.0.0:5432 -credential_file=/cs-field-guide/continuous-deployment-${DEPLOYMENT}.json

  django:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    command: /docker_venv/bin/gunicorn -c ./gunicorn.conf.py -b :8080 config.wsgi --reload
    volumes:
      - .:/cs-field-guide
    environment:
      - USE_DOCKER=yes
      - DJANGO_SETTINGS_MODULE=config.settings.database_proxy
      - GOOGLE_CLOUD_SQL_DATABASE_USERNAME=${GOOGLE_CLOUD_SQL_DATABASE_USERNAME}
      - GOOGLE_CLOUD_SQL_DATABASE_PASSWORD=${GOOGLE_CLOUD_SQL_DATABASE_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - INCLUDE_INCONTEXT_L10N=${INCLUDE_INCONTEXT_L10N}
    depends_on:
      - cloud_sql_proxy

  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    volumes:
      - ./csfieldguide/:/app/
      - /app/node_modules
    depends_on:
      - django
